### ISSUE TITLE
Out-of-tree builds can't find lib SofaComponentGeneral

### ISSUE THREAD

**Issue by marques-bruno** [SofaDefrost/plugin.SofaPython3#137]
When building SofaPython3 as out-of-tree build, linker can't find SofaComponentGeneral.
Though, CMAKE_PREFIX_PATH is properly set to SOFA's install dir, SofaPython3's CMakeLists.txt performs the SofaGeneral findPackage and target_link_libraries does include SofaComponentGeneral.

**Comment by jnbrunet** [comment]
You need to add `find_package(SofaComponentGeneral REQUIRED)`

I added it to my PR #136 as a quick fix

**Comment by ngvpho** [comment]
Hello,
I built plugin.Sofapython3 by out-of-tree build, however, in the sofa_root build has only two files:
![Screenshot from 2019-12-29 23-47-54](https://user-images.githubusercontent.com/50490676/71558383-12608d80-2a96-11ea-8729-481c4bb32e24.png)
And I cannot load sofa_python3.
Could you please help me to solve this problem?

**Comment by damienmarchal** [comment]
Hi Phi,
Can you give us more details on which sofa version you are using for the out of tree build ? 
Is this a pre-made binary version that we ship or your own ? On my side not sure SofaPython3 can be build out of tree with something other than an up to date sofa build.

**Comment by ngvpho** [comment]
Hi Damien,
I installed Sofa v19.06, which got from this link in sofa build:
git clone -b v19.06 https://github.com/sofa-framework/sofa.git sofa/src/
The errors are as attached file bellow:
[Error in installing sofapython3.pdf](https://github.com/SofaDefrost/plugin.SofaPython3/files/4025989/Error.in.installing.sofapython3.pdf)

**Comment by jnbrunet** [comment]
Hi Pho,

@damienmarchal is right, you will need to build the development version of sofa as SofaPython3 is still isn't released yet.

Before starting, let's define some path variables :

`$ SOFA_SRC=$HOME/Documents/MySofa/P-sofa/src`
`$ SOFA_BLD=$HOME/Documents/MySofa/P-sofa/build`
`$ SP3_SRC=$HOME/Documents/MySofa/SofaPython3`
`$ SP3_BLD=$HOME/Documents/MySofa/SofaPython3/build`

_(Make sure those paths are good)_

### 1. Building the development version of Sofa

Checkout the master branch of sofa and build it
```
$ cd $SOFA_SRC
$ git checkout master
$ git pull
$ cd $SOFA_BLD
$ cmake $SOFA_SRC
$ make
$ make install
```
_(The last step `make install` is very important here, it should install Sofa's binaries in the directory `$SOFA_BLD/install`.)_

### 2. Building the plugin SofaPython3

It is in this step that we need to give CMake the path to Sofa's installation path of the last step.
```
$ cd $SP3_SRC
$ git pull
$ cd $SP3_BLD
$ cmake -DCMAKE_PREFIX_PATH=$SOFA_BLD/install/lib/cmake $SP3_SRC
$ make
```

At this point, make sure you can find the file `$SP3_BLD/lib/libSofaPython3.so`
### 3. Running Sofa with the plugin
Finally, launch Sofa with
 `./$SOFA_BLD/bin/runSofa -l $SP3_BLD/lib/libSofaPython3.so`

**Comment by damienmarchal** [comment]
Thank you for pointing the weakness of the out-of-source build documentation. 

So here is a more detailled one that I just tested and that work.

Sofa
====
1) get the sofa source code using git to clone the *master* branch from https://github.com/sofa-framework/sofa.git sofa/src/ 
type: 
```console
git clone https://github.com/sofa-framework/sofa.git sofa/src/ 
```
2) compile sofa following the video tutorial. At this step, please test that you have a runSofa application in the "bin" directory. If this is not the case no need to go further. 

3) once this is done in the sofa build directory do an install step
```console
make install
```
or with ninja (if you use it)
```console
ninja install
```
Now you should have a directory called "install"
```console
/home/ho-lab/Documents/MySofa/P-sofa/build/install
```

At this point you are ready to make an out-of-tree build of the python plugin. 

SofaPython3
==========
You can keep the organization of your directory (the one you are specifying in the pdf file you send).  With SofaPython3 next to the P-sofa folder. 

So 
1) get the SofaPython3 source code using git to clone the *master* branch.
```console
git clone git@github.com:SofaDefrost/plugin.SofaPython3.git 
```

2) use cmake to configure the build script specifying the CMAKE_PREFIX_PATH to point to the location of *your* sofa installation. So in your case it should be
```console
CMAKE_PREFIX_PATH=/home/ho-lab/Documents/MySofa/P-sofa/build/install
```
When you click on generate you shouldn't have error/failure and you normally don't need to specify the PYTHON_ROOT_DIR or Python_EXECUTABLE. This only happens if you have already compiled your sofa version with python2.7 enabled. So by default don't do that. At this step you now can compile the python plugin. 

3) compile the plugin by going into your SofaPython3 build directory and type 
```ninja``` or ```make``` depending on the build system you use. 

When the compilation is done you should have in the SofaPython3 build directory a subdirectory called "lib" with this content: ```libSofaPython3.so  libSofaPython3.so.1.0  site-packages```.

**Comment by damienmarchal** [comment]
Haha :@jnbrunet  & I responded at he same time ;)
Thanks @jnbrunet

**Comment by jnbrunet** [comment]
Damn @damienmarchal , 1 minute between our replies!

Indeed, I forget about the python package. There are many ways to do it, mine is:

4. Install the SofaPython3 python package into your python's user site directory
`ln -sFfv $(find $SP3_BLD/lib/site-packages ! -name *.py -d 1) $(python3 -m site --user-site)`
This will create symbolic links, so you only need to do it once after the compilation

I'll edit my answer to add this step

**Comment by ngvpho** [comment]
Thank you so much @jnbrunet and @damienmarchal 
Now i can run sofa python 3 by using command: ./$SOFA_BLD/bin/runSofa -l $SP3_BLD/lib/libSofaPython3.so. 
However when loading a .py file it appeared errors as my attached file: 
![Screenshot from 2020-01-08 17-09-52](https://user-images.githubusercontent.com/50490676/71961212-3d877180-323a-11ea-8b0c-c03a8f293e67.png)

**Comment by damienmarchal** [comment]
Hi Pho,

There is an [Error] message saying that it cannot load /lib/SofaPython3.so

When you are typing:
```console
/$SOFA_BLD/bin/runSofa -l $SP3_BLD/lib/libSofaPython3.so
```
Did you set the environment variable $SP3_BLD before ? Otherwise it is empty, so it would not be surprising that the plugin does not load.

If you don't know how to do this in Linux here is a starting point:
https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-environment-variables-in-linux/

DM.

**Comment by ngvpho** [comment]
Hi Damien,
Many thanks for your quick reply. Actually, I already set $SP3_BLD, and in lib folder also includes 3 files you required: libSofaPython3.so  libSofaPython3.so.1.0  site-packages
![Screenshot from 2020-01-08 21-15-52](https://user-images.githubusercontent.com/50490676/71977871-4b9ab980-325d-11ea-859f-3815e4527c8b.png)
Now I type: ln -sFfv $(find $SP3_BLD/lib/site-packages ! -name *.py -d 1) $(python3 -m site --user-site), it warned as follows:
![Screenshot from 2020-01-08 21-27-09](https://user-images.githubusercontent.com/50490676/71978090-dbd8fe80-325d-11ea-9e95-ccda743ebf52.png)
Then, I types: ./$SOFA_BLD/bin/runSofa -l $SP3_BLD/lib/libSofaPython3.so, it appears error:
![Screenshot from 2020-01-08 21-31-17](https://user-images.githubusercontent.com/50490676/71978351-746f7e80-325e-11ea-97b3-cf68ab36a4b2.png)
 "pybind11::error_already_set" ? I already install pybind11 in this image:
![Screenshot from 2020-01-08 21-21-19](https://user-images.githubusercontent.com/50490676/71978414-a2ed5980-325e-11ea-8cb4-7e14123d38b1.png)
Pho

**Comment by jnbrunet** [comment]
Hey Pho,

My bad, I was on Mac osx when testing.

Try with 
```
ln -sFfv $(find $SP3_BLD/lib/site-packages -maxdepth 1 -not -name "*.py") $(python3 -m site --user-site)
```
instead.

**Comment by ngvpho** [comment]
Hi Jnbrunet,
Thank you for your answer.
I tried with your suggestion, it appears error:
![Screenshot from 2020-01-08 22-52-02](https://user-images.githubusercontent.com/50490676/71983236-a9350300-3269-11ea-9fc0-5695c1603c53.png).
Actually, there is no site-packages folder in this path: ./lib/python3.7/..
![Screenshot from 2020-01-08 22-53-49](https://user-images.githubusercontent.com/50490676/71983383-fadd8d80-3269-11ea-95ff-71a194f90b9a.png)
I tried to install site-packages for python3 in many methods, it errors:
![Uploading Screenshot from 2020-01-08 22-56-22.png…]()

**Comment by jnbrunet** [comment]
Then simply create it...
``` bash
$ mkdir -p $HOME/.local/lib/python3.7/site-packages
```

site-packages isn't a package. It is the directory where python looks to find packages.

**Comment by ngvpho** [comment]
Hi Jnbrunet and Damien,
Thank you so much for your help. Now i can open sofapython3.
Pho

**Comment by ngvpho** [comment]
Hello,
When adding file plugin_list.conf.default in ~/Documents/Pho.Nguyen/MySofa/sofa/build/lib, I can open sofapython3 but it appear error:
![Screenshot from 2020-01-10 19-25-10](https://user-images.githubusercontent.com/50490676/72146203-4feee000-33df-11ea-9782-1622c60bc77d.png)
When remove that file, I cannot open sofapython3.
What should I do in this case?

**Comment by damienmarchal** [comment]
Can you provide more details (screenshot) on the two results because I d'ont understand yet what you are saying;

**Comment by ngvpho** [comment]
Hi Damien,
Last time, after building plugin sofapython3, I had to detele the file: "plugin_list.conf.default" in this folder
![Screenshot from 2020-01-10 21-09-27](https://user-images.githubusercontent.com/50490676/72152175-9814ff00-33ed-11ea-8cf3-5eb3515996b5.png)
and I can load the soft-eel.py file. Today, the errors happened:   
if delete the file: "plugin_list.conf.default", error is as follows:
![Screenshot from 2020-01-10 21-13-18](https://user-images.githubusercontent.com/50490676/72152357-12de1a00-33ee-11ea-98f0-ec6520447a1d.png)
and in case I keep the file: "plugin_list.conf.default", error is:
![Screenshot from 2020-01-10 21-04-30](https://user-images.githubusercontent.com/50490676/72152415-4456e580-33ee-11ea-9588-172636b20e0f.png)

**Comment by jnbrunet** [comment]
hey @ngvpho 

Do not delete the file _plugin_list.conf.default_.

It seems you are missing the ".so" extension to your plugin. Change
```bash
$ ./runSofa $SP3_BLD/lib/libSofaPython3
```
for
```bash
$ ./runSofa $SP3_BLD/lib/libSofaPython3.so
```

Next, your are loading the the old **SofaPython** plugin. This plugin is incompatible with  the plugin **SofaPython3**.  To remove it, first unset the SofaPython option in the compilation of Sofa.

```bash 
$ cd $SOFA_BLD
$ cmake-gui .
```
and uncheck the **PLUGIN_SOFAPYTHON**  option.
Rebuild Sofa
```bash
$ make install
```
And make sure the SofaPython plugin isn't in the file `$SOFA_BLD/config/loadedPlugins.ini`

**Comment by ngvpho** [comment]
Hi @jnbrunet,
After following your suggestion, it still errors:
![Screenshot from 2020-01-13 22-14-02](https://user-images.githubusercontent.com/50490676/72258772-399c8a80-3652-11ea-9ac2-14d5d93f9a6e.png)
These folders have:
![Screenshot from 2020-01-13 22-18-21](https://user-images.githubusercontent.com/50490676/72258966-b6c7ff80-3652-11ea-9940-923bd9bd442a.png)
![Screenshot from 2020-01-13 22-16-04](https://user-images.githubusercontent.com/50490676/72258975-bb8cb380-3652-11ea-9819-88667eee46fb.png)

**Comment by damienmarchal** [comment]
I think the -l is missing in:
```console
$ ./runSofa $SP3_BLD/lib/libSofaPython3.so
```
Shouldn't it be:
```console
$ ./runSofa -l $SP3_BLD/lib/libSofaPython3.so
```

**Comment by ngvpho** [comment]
Hi @damienmarchal and @jnbrunet ,
Thank you so much for your help. Now it works.^^

**Comment by jnbrunet** [comment]
Alright, I think we can close this issue now. The initial bug of this issue was fixed by #136 .

**Comment by ngvpho** [comment]
Hi, 

Last time, I successfully installed sofa python3 in ubuntu19.10. Recently, I am installing sofa python3 on another computer running in ubuntu20.04. The configuration and compile were fine without any problems. But, it lacked file libSofaPython3.so.01 in $SP3_BLD/lib/. See following image:
![Screenshot from 2020-11-20 10-48-11](https://user-images.githubusercontent.com/50490676/99747503-fcc8dc00-2b1d-11eb-83d3-ce2cdf8f95d6.png)
and then, when running "./runSofa -l $SP3_BLD/lib/libSofaPython3.so", it appeared main screen, and detect .py file, but cannot load them. See following image:
![Screenshot from 2020-11-20 10-40-15](https://user-images.githubusercontent.com/50490676/99747627-474a5880-2b1e-11eb-9d5f-54651b833616.png)

I don't know why Sofa cannot load "plugin Sp3".
Anyone can help me?

Best,
Pho

**Comment by damienmarchal** [comment]
Hello @ngvpho, 

Thanks for reporting the problem. 

Instead of loading the plugin with the -I option in the command line can you load it manually using the menu "View/PluginManager..." ? Then try to load the scene. 

In that case does it work ? If it is not the case then maybe it is a bug somewere  that we need to investigate. @jnbrunet  does it ring a bell to you ?

**Comment by jnbrunet** [comment]
Hi @ngvpho ,

It cannot find it because it isn't in the SOFA's plugins directory (`$SOFA_ROOT/plugins`) nor the `SOFA_PLUGIN_PATH` environment variable. It finds it the first time with the `runSofa -l `, but at the line `requiredPlugin(SofaPython3)` SOFA tries to find it a second time (without even verifying that it is already loaded...), and cannot find it.

Since you already loaded the plugin with the runSofa's `-l` option, normally you don't have to add it a second time with the  `requiredPlugin(SofaPython3)`, so you could remove the line from your scene.

**Comment by damienmarchal** [comment]
In general at Defrost we recommand to always put all the required plugin in every scenes. Doing so clearly states what are the needs for the scene to run and makes them much more robust (and sharable) because they makes no assumption on how is configure/initialized the execution environment. 

If doing so rises a warning/error message then I think we should fix this behavior instead of fixing the scene. But I'm surprise this the case ?

**Comment by jnbrunet** [comment]
Hi @damienmarchal ,

Of course. However, here you need the plugin to be able to load the scene (.py). In this case, @ngvpho explicitly stated the complete path to the plugin via the `-l` option so that runSofa can load its python scene.  But this path isn't automatically added to the plugin search paths of SOFA.

**Comment by damienmarchal** [comment]
@jnbrunet it is unclear to me if you think:
-  the error message is legitimate and thus nothing has to be done 
-  the error message is not legitimate and if we should fix the plugin manager so that it stop printing that.

**Comment by jnbrunet** [comment]
Hey @damienmarchal ,

The error message is legitimate: you asked SOFA to find the plugin SofaPython3 via a `requiredPlugin` component, but it cannot find it. SofaPython3 has been compiled out-of-source and the build directory of the plugin isn't in SOFA's plugin paths.

SOFA has no way to tell if the plugin is already loaded (in this case, via the `-l` option) since it does its comparison between plugins by first loading them in memory and getting the result of the global method `getModuleName()`, usually defined in the `init.cpp` file of the plugin.

**Comment by damienmarchal** [comment]
Ok, on my side I don't think RequiredPlugin is equivalent to FindPlugin neither LoadPlugin, it is just saying it is required and consequently if it is already "there", the requierement is fullfill and I see no good reason why to should print an error. 

About the fact that "SOFA has no way to tell if the plugin is already loaded"...
Shouldn't the existing PluginManage::isPluginLoaded() and/or the PluginManager::m_pluginMap may be of some help there ? 

EDIT: If I have some time I will try to make some tests to see if it is doable.

**Comment by jnbrunet** [comment]
Unfortunately, the `PluginManage::isPluginLoaded()` doesn't exactly do this. It takes as an argument a plugin **path**, than tries to load it and compare the paths of both plugins:

```cpp
bool PluginManager::pluginIsLoaded(const std::string& plugin)
{
    std::string pluginPath = plugin;

    if (!FileSystem::isFile(plugin)) {
        pluginPath = findPlugin(plugin);
    }

    return m_pluginMap.find(pluginPath) != m_pluginMap.end();
}
```

I agree that `RequiredPlugin(plugin_name)` should check if a loaded plugin has its "name" (ie `getModuleName()`) equals to "plugin_name". This is could be a useful PR on SOFA's side, but not related to SP3 however.

**Comment by ngvpho** [comment]
Hi @Damien,

I can find SofaPython3 in plugin manager
![Screenshot from 2020-12-07 10-28-08](https://user-images.githubusercontent.com/50490676/101299845-eee1bd80-3876-11eb-9f53-ea8f360b04d4.png)

Hi @jnbrunet 

I run the command again without -l, but it is still error.
![Screenshot from 2020-12-07 10-29-42](https://user-images.githubusercontent.com/50490676/101299919-2d777800-3877-11eb-887d-f6d6ad45b4a3.png)
Do you have any ideas?
Best,
Pho

**Comment by jnbrunet** [comment]
Hey @ngvpho ,

The "-l" parameter expects a path to a plugin library (.so), example `runSofa -l libSofaPython3.so`. If you remove the "-l" but let the path there, than SOFA will see this path as a scene to load (ex `runSofa libSofaPython3.so`, which is wrong here, libSofaPython3.so is not a scene but a plugin, which is why you are having this error.   Simply remove the path from the command line arguments unless you prefix it with the "-l".

JN

**Comment by ngvpho** [comment]
Hi @jnbrunet,

Ok, I can load it.
Thanks for your help. ^^

Best,
Pho
